## Ejemplo de Regresión con TensorFlow

In [2]:
import pandas as pd
import tensorflow as tf

In [5]:
casas = pd.read_csv('./Data/precios_casas.csv')

In [6]:
casas.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [7]:
casas_x = casas.drop('median_house_value', axis = 1)

In [8]:
casas_x.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  
0      1015.0       472.0         1.4936  
1      1129.0       463.0         1.8200  
2       333.0       117.0         1.6509  
3       515.0       226.0         3.1917  
4       624.0       262.0         1.9250

In [9]:
casas_y = casas['median_house_value']

In [10]:
casas_y.head()

0    66900.0
1    80100.0
2    85700.0
3    73400.0
4    65500.0
Name: median_house_value, dtype: float64

### Separar en Train and Test

In [11]:
from sklearn.model_selection import train_test_split

In [13]:
x_train, x_test, y_train, y_test = train_test_split(casas_x, casas_y, test_size = 0.30)

In [14]:
x_train.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
7178     -118.33     34.16                44.0       2705.0           649.0   
12030    -121.41     38.64                38.0       1384.0           287.0   
13038    -121.86     37.00                16.0       8638.0          1392.0   
10292    -120.05     36.98                16.0       3705.0           739.0   
14403    -122.12     37.69                35.0       2681.0           508.0   

       population  households  median_income  
7178       1676.0       654.0         3.4286  
12030       682.0       280.0         1.9167  
13038      3706.0      1251.0         5.5030  
10292      2463.0       697.0         2.5288  
14403      1580.0       536.0         4.1042

In [15]:
x_test.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
5631     -118.18     34.03                39.0        609.0           145.0   
16391    -122.54     37.91                48.0       2924.0           489.0   
12747    -121.79     38.68                24.0       3794.0           848.0   
13564    -121.97     37.40                17.0       2937.0           558.0   
16536    -122.66     38.44                17.0       5815.0           898.0   

       population  households  median_income  
5631        690.0       134.0         2.9167  
16391      1159.0       505.0         5.6302  
12747      2225.0       864.0         2.8068  
13564      1662.0       533.0         5.8792  
16536      2614.0       887.0         4.3657

In [16]:
y_train.head()

7178     247900.0
12030     64400.0
13038    351800.0
10292     61800.0
14403    179100.0
Name: median_house_value, dtype: float64

In [17]:
y_test.head()

5631     145800.0
16391    489000.0
12747     95300.0
13564    255500.0
16536    215900.0
Name: median_house_value, dtype: float64

In [18]:
from sklearn.preprocessing import MinMaxScaler

### Normalización

In [19]:
normalizador = MinMaxScaler()

In [20]:
normalizador.fit(x_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [21]:
x_train = pd.DataFrame(data=normalizador.transform(x_train), columns=x_train.columns,index=x_train.index)

In [22]:
x_train #Los datos han sido normalizados,estan entre 0 y 1

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
7178    0.599602  0.172157            0.843137     0.071253        0.118464   
12030   0.292829  0.648247            0.725490     0.036431        0.052285   
13038   0.248008  0.473964            0.294118     0.227653        0.254296   
10292   0.428287  0.471838            0.294118     0.097614        0.134918   
14403   0.222112  0.547290            0.666667     0.070621        0.092687   
...          ...       ...                 ...          ...             ...   
646     0.728088  0.049947            0.529412     0.024252        0.019378   
14601   0.218127  0.520723            0.647059     0.057915        0.096527   
6327    0.607570  0.144527            0.686275     0.029867        0.042048   
6019    0.610558  0.166844            0.686275     0.075603        0.096527   
350     0.742032  0.031881            0.333333     0.111058        0.147898   

       population  households  median_income  
7178     0.046890    0.125867       0.201977  
12030    0.019031    0.053778       0.097709  
13038    0.103787    0.240941       0.345037  
10292    0.068948    0.134156       0.139922  
14403    0.044200    0.103123       0.248569  
...           ...         ...            ...  
646      0.008717    0.018504       0.549799  
14601    0.033353    0.102352       0.261879  
6327     0.017125    0.043562       0.141529  
6019     0.038342    0.108712       0.324713  
350      0.058886    0.148805       0.247403  

[11900 rows x 8 columns]

In [23]:
x_test = pd.DataFrame(data=normalizador.transform(x_test), columns=x_test.columns,index=x_test.index)

In [24]:
x_test.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
5631    0.614542  0.158342            0.745098     0.016001        0.026325   
16391   0.180279  0.570670            0.921569     0.077026        0.089214   
12747   0.254980  0.652497            0.450980     0.099960        0.154845   
13564   0.237052  0.516472            0.313725     0.077369        0.101828   
16536   0.168327  0.626993            0.313725     0.153236        0.163985   

       population  households  median_income  
5631     0.019255    0.025636       0.166674  
16391    0.032400    0.097147       0.353809  
12747    0.062278    0.166345       0.159094  
13564    0.046498    0.102544       0.370981  
16536    0.073180    0.170779       0.266603

In [25]:
casas.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [29]:
longitude = tf.feature_column.numeric_column('longitude')
latitude = tf.feature_column.numeric_column('latitude')
housing_median_age = tf.feature_column.numeric_column('housing_median_age')
total_rooms = tf.feature_column.numeric_column('total_rooms')
total_bedrooms = tf.feature_column.numeric_column('total_bedrooms')
population = tf.feature_column.numeric_column('population')
households = tf.feature_column.numeric_column('households')
median_income = tf.feature_column.numeric_column('median_income')

In [30]:
columnas = (longitude, latitude, housing_median_age, total_rooms, total_bedrooms, population, households, median_income)

### Learning (Aprendizaje)

In [32]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [33]:
funcion_entrada = tf.estimator.inputs.pandas_input_fn(x = x_train, y = y_train, batch_size = 10, num_epochs = 1000, shuffle = True)

In [34]:
modelo = tf.estimator.DNNRegressor(hidden_units=[10,10,10], feature_columns=columnas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpsxf8h67w', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [35]:
modelo.train(input_fn = funcion_entrada, steps = 8000)

Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmpsxf8h67w/model.ckpt.
INFO:tensorflow:loss = 737813900000.0, step = 0
INFO:tensorflow:global_step/sec: 187.766


### Predicción

In [36]:
funcion_entrada_prediccion = tf.estimator.inputs.pandas_input_fn(x = x_test, batch_size=10, num_epochs=1, shuffle= False)

In [37]:
generador_predicciones = modelo.predict(funcion_entrada_prediccion)

In [38]:
predicciones = list(generador_predicciones)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpsxf8h67w/model.ckpt-8000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [39]:
predicciones

},
 {'predictions': array([229030.22], dtype=float32)},
 {'predictions': array([138901.62], dtype=float32)},
 {'predictions': array([219957.02], dtype=float32)},
 {'predictions': array([241025.78], dtype=float32)},
 {'predictions': array([204447.39], dtype=float32)},
 {'predictions': array([229958.36], dtype=float32)},
 {'predictions': array([160459.23], dtype=float32)},
 {'predictions': array([229773.66], dtype=float32)},
 {'predictions': array([200415.2], dtype=float32)},
 {'predictions': array([189387.73], dtype=float32)},
 {'predictions': array([181768.94], dtype=float32)},
 {'predictions': array([184703.14], dtype=float32)},
 {'predictions': array([214292.23], dtype=float32)},
 {'predictions': array([201596.95], dtype=float32)},
 {'predictions': array([225418.72], dtype=float32)},
 {'predictions': array([184243.8], dtype=float32)},
 {'predictions': array([189902.73], dtype=float32)},
 {'predictions': array([206890.83], dtype=float32)},
 {'predictions': array([203984.36], dtype=flo

In [40]:
predicciones_finales = []
for prediccion in predicciones:
    predicciones_finales.append(prediccion['predictions'])

In [41]:
predicciones_finales

ype=float32),
 array([203697.88], dtype=float32),
 array([267596.6], dtype=float32),
 array([224914.03], dtype=float32),
 array([200271.28], dtype=float32),
 array([185894.33], dtype=float32),
 array([219161.23], dtype=float32),
 array([175550.31], dtype=float32),
 array([194389.89], dtype=float32),
 array([207985.81], dtype=float32),
 array([222150.02], dtype=float32),
 array([207756.66], dtype=float32),
 array([201146.22], dtype=float32),
 array([206218.23], dtype=float32),
 array([175978.23], dtype=float32),
 array([209922.02], dtype=float32),
 array([192981.86], dtype=float32),
 array([191609.72], dtype=float32),
 array([160719.4], dtype=float32),
 array([174165.38], dtype=float32),
 array([204942.1], dtype=float32),
 array([221829.75], dtype=float32),
 array([216053.14], dtype=float32),
 array([201450.44], dtype=float32),
 array([209759.92], dtype=float32),
 array([197115.92], dtype=float32),
 array([185925.61], dtype=float32),
 array([228615.], dtype=float32),
 array([214320.14],

In [42]:
from sklearn.metrics import mean_squared_error

In [43]:
mean_squared_error(y_test, predicciones_finales) ** 0.5

103233.50099272151