## TensorFlow - Sintaxis Básica

In [1]:
import tensorflow as tf

In [18]:
mensaje1 = tf.constant("Hola ")
mensaje2 = tf.constant("Mundo")

In [19]:
print(mensaje1)

tf.Tensor(b'Hola', shape=(), dtype=string)


In [20]:
type(mensaje1)

tensorflow.python.framework.ops.EagerTensor

In [22]:
with tf.compat.v1.Session() as session:
    mensaje1 = tf.constant("Hola ")
    mensaje2 = tf.constant("Mundo")
    resultado = session.run( mensaje1 + mensaje2)

In [23]:
resultado

b'Hola Mundo'

In [24]:
with tf.compat.v1.Session() as session:
    print(session.run( tf.constant(10) + tf.constant(5)))

15


In [36]:
constante = tf.constant(15)
matriz1 = tf.fill((6,6),10)
matriz2 = tf.random.normal((5,5))
matriz3 = tf.random.uniform((4,4), minval=0, maxval=5)
matriz_ceros = tf.zeros((2,2))
matriz_unos = tf.ones((3,3))

In [44]:
operaciones = [constante, matriz1, matriz2, matriz3, matriz_ceros, matriz_unos]

In [45]:
with tf.compat.v1.Session() as session:
    for op in operaciones:
        print(session.run(op))
        print("\n")

15


[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


[[ 0.0612001   1.1640983  -1.772536    1.7879703   0.33963495]
 [ 0.55807185 -0.21320987 -0.9370549  -0.34811106 -1.2815862 ]
 [-0.06193787  1.170535    0.6814621   1.7510641   1.220241  ]
 [ 0.9113978   0.3618879  -2.1057942  -1.2925603  -1.0232202 ]
 [-1.6405864  -1.0378088   1.3739486  -0.21259108  2.0152366 ]]


[[0.63930094 1.9078279  1.0725361  2.6460843 ]
 [1.7990935  1.7926282  3.0790174  4.206271  ]
 [2.055388   3.76603    1.5117407  0.70524216]
 [3.9861755  2.720769   4.3827033  1.7040825 ]]


[[0. 0.]
 [0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


