## Variables y Placeholders

In [1]:
import tensorflow as tf

In [2]:
tensor = tf.random.uniform((5,5),0,1)

In [3]:
variable = tf.Variable(initial_value = tensor)

In [4]:
print(variable)

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[0.8863311 , 0.96319616, 0.36266887, 0.41382778, 0.986146  ],
       [0.83589995, 0.9218315 , 0.08589625, 0.00184298, 0.72541416],
       [0.02022994, 0.9104527 , 0.11797678, 0.6090926 , 0.66780233],
       [0.4862255 , 0.8517803 , 0.05543029, 0.553825  , 0.21603   ],
       [0.14239597, 0.8272104 , 0.7964349 , 0.7285104 , 0.7081382 ]],
      dtype=float32)>


In [5]:
inicializador = tf.compat.v1.global_variables_initializer()

In [15]:
with tf.compat.v1.Session() as session:
    session.run(inicializador)
    print(session.run(variable))

[[0.9217888  0.3279444  0.17307162 0.99590826 0.22854662]
 [0.4682175  0.3544253  0.34193635 0.9034368  0.39552677]
 [0.62279344 0.3159641  0.4833883  0.3704908  0.77794695]
 [0.29388428 0.24417198 0.24271381 0.26049316 0.9857795 ]
 [0.6657256  0.50502145 0.04737711 0.99098825 0.50197124]]


## Placeholders

In [22]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 
incognita = tf.placeholder(tf.float32, shape = (20,20))
print(incognita)

Tensor("Placeholder_1:0", shape=(20, 20), dtype=float32)
