## Red Neuronal con TensorFlow

In [16]:
import tensorflow as tf
import numpy as np

In [11]:
aleatorio_a = np.random.uniform(0,50,(4,4))
print(aleatorio_a)

[[18.48196923 21.5044268  15.7734493  26.53118481]
 [25.39413802  2.3475488  33.65366483 25.94307551]
 [40.00188665  5.32062627 20.04641086 42.26534628]
 [33.11276325 15.83017936 15.17594654 47.17595634]]


In [13]:
aleatorio_b = np.random.uniform(0,50,(4,1))
print(aleatorio_b)

[[33.6864711 ]
 [16.79330568]
 [23.53560036]
 [17.71192342]]


In [22]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 

a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [31]:
suma = a + b
multiplicacion = a * b

In [42]:
with tf.Session() as sesion:
    resultado_suma = sesion.run(suma, feed_dict = {a:10, b:20})
    print(resultado_suma)

30.0


In [43]:
with tf.Session() as sesion:
    resultado_suma = sesion.run(suma, feed_dict = {a:aleatorio_a, b:aleatorio_b})
    print(resultado_suma)

[[52.16844  55.190895 49.45992  60.217655]
 [42.187447 19.140856 50.446968 42.73638 ]
 [63.53749  28.856228 43.582012 65.80095 ]
 [50.824684 33.542103 32.88787  64.88788 ]]


In [45]:
with tf.Session() as sesion:
    resultado_multiplicacion = sesion.run(multiplicacion, feed_dict = {a:aleatorio_a, b:aleatorio_b})
    print(resultado_multiplicacion)

[[622.59235  724.40826  531.3518   893.74194 ]
 [426.45154   39.423103 565.1563   435.67    ]
 [941.46844  125.22414  471.80432  994.7403  ]
 [586.4907   280.38293  268.7952   835.57697 ]]


## Ejemplo Red Neuronal

In [47]:
caracteristicas = 10
neuronas = 4

In [81]:
#Las coincidencias entre caracteristicas y neuronas son obligatorias
x = tf.placeholder(tf.float32,(None,caracteristicas))
w = tf.Variable(tf.random.normal([caracteristicas,neuronas]))
b = tf.Variable(tf.ones([neuronas]))

In [82]:
multiplicacion = tf.matmul(x, w)

In [83]:
z = tf.add(multiplicacion, b)

In [84]:
activacion = tf.sigmoid(z)

In [85]:
inicializacion = tf.global_variables_initializer()

In [86]:
valores_x = np.random.random([1,caracteristicas])
print(valores_x)

[[0.72772169 0.35302124 0.80579088 0.03581484 0.72797691 0.2535635
  0.60319027 0.91875048 0.58549814 0.55168586]]


In [87]:
with tf.Session() as session:
    session.run(inicializacion)
    resultado = session.run(activacion, feed_dict= {x:valores_x})

In [89]:
print(resultado)

[[0.9138119  0.99842465 0.93472725 0.98457503]]
