## Numpy - Arrays

In [1]:
import numpy as np

In [2]:
numeros = [1,2,3,4]

In [3]:
array = np.array(numeros)

In [4]:
array

array([1, 2, 3, 4])

In [5]:
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
np.arange(0,30,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
np.linspace(0,30,10)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        , 23.33333333, 26.66666667, 30.        ])

In [11]:
np.linspace(0,50,5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [12]:
np.random.randint(0,100,5)

array([57, 54, 28, 34, 34])

In [13]:
array = np.random.randint(0,100,10)

In [14]:
array

array([41, 48, 40, 87, 53, 92, 71, 89, 51, 31])

In [15]:
array.max()

92

In [16]:
array.argmax()

5

In [17]:
array.min()

31

In [18]:
array.mean()

60.3

In [19]:
array

array([41, 48, 40, 87, 53, 92, 71, 89, 51, 31])

In [20]:
array.reshape(5,2)

array([[41, 48],
       [40, 87],
       [53, 92],
       [71, 89],
       [51, 31]])

In [21]:
array

array([41, 48, 40, 87, 53, 92, 71, 89, 51, 31])

In [22]:
array = array.reshape(5,2)

In [23]:
array

array([[41, 48],
       [40, 87],
       [53, 92],
       [71, 89],
       [51, 31]])

In [24]:
array[2,0]

53

In [25]:
array[0,1]

48

In [26]:
filtro = array > 30
array2 = array[filtro]

In [27]:
array2

array([41, 48, 40, 87, 53, 92, 71, 89, 51, 31])